# Generated by Django 4.1.1 on 2022-10-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bodydatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cloth/')),
            ],
        ),
    ]
