# Generated by Django 4.1.1 on 2022-11-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bgremovedimgmodel_alter_userimgmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='originalPoseImgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalPoseImg', models.TextField()),
            ],
        ),
    ]
